// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq1T5bLUA-MWtdJY5wsCdTt8gmjcYnzO8',
    appId: '1:494830525753:web:538c6f33ac16164b061ce8',
    messagingSenderId: '494830525753',
    projectId: 'flutter-chat-app-a15d2',
    authDomain: 'flutter-chat-app-a15d2.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a15d2.firebasestorage.app',
    measurementId: 'G-9MT6Y1XYRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTfdv0ockBAGV9jnahnz-RoJfHd8Osj7Q',
    appId: '1:494830525753:android:a2ed31f3ca24c36a061ce8',
    messagingSenderId: '494830525753',
    projectId: 'flutter-chat-app-a15d2',
    storageBucket: 'flutter-chat-app-a15d2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAsGKfF8SqILdlpX6rhNT7NU6bbrvd6ug',
    appId: '1:494830525753:ios:f46719e4c45764e6061ce8',
    messagingSenderId: '494830525753',
    projectId: 'flutter-chat-app-a15d2',
    storageBucket: 'flutter-chat-app-a15d2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAsGKfF8SqILdlpX6rhNT7NU6bbrvd6ug',
    appId: '1:494830525753:ios:f46719e4c45764e6061ce8',
    messagingSenderId: '494830525753',
    projectId: 'flutter-chat-app-a15d2',
    storageBucket: 'flutter-chat-app-a15d2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq1T5bLUA-MWtdJY5wsCdTt8gmjcYnzO8',
    appId: '1:494830525753:web:f1677dc935d71cc1061ce8',
    messagingSenderId: '494830525753',
    projectId: 'flutter-chat-app-a15d2',
    authDomain: 'flutter-chat-app-a15d2.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a15d2.firebasestorage.app',
    measurementId: 'G-YLE37LF9PJ',
  );
}
